### ISSUE TITLE
HTTPS Protocol is NOT supported

### ISSUE THREAD

**Issue by ye** [cloudflare/raven-lua#11]
It looks like rave-lua doesn't support HTTPS yet as of March 2016 as seen in [`raven.lua`](../blob/master/raven.lua#L394). Unfortunately, this is a deal-breaker for a lot of folks out there because the [hosted version of Sentry only supports HTTPS](https://docs.getsentry.com/hosted/clients/java/config/)!

**Comment by mattrobenolt** [comment]
See: https://github.com/cloudflare/raven-lua/pull/4 but I was also told this approach isn't very secure and/or good. I'm not a Lua person, but was just hacking around on this a while back, so not sure the correct approach.

**Comment by ye** [comment]
@mattrobenolt why wasn't it very secure / good? What's the hold back? That PR was more than 1 year old!

**Comment by mattrobenolt** [comment]
I don't know, someone who knew more Lua than me said it was bad. That's all I remember.

**Comment by jdesgats** [comment]
Solved by #21
