### ISSUE TITLE
Discarded invalid value for parameter 'tags' 

### ISSUE THREAD

**Issue by ye** [cloudflare/raven-lua#12]
In the project home page's README synopsis, [the example](https://github.com/cloudflare/raven-lua/blob/master/README.md#synopsis) code to initialize `rvn` reads:

``` lua
    -- http://pub:secret@127.0.0.1:8080/sentry/proj-id
    local rvn = raven:new("http://pub:secret@127.0.0.1:8080/sentry/proj-id", {
       tags = { foo = "bar" },
    })
    ...
```

However, it turns out that `tags` parameter doesn't seem to be legal. As seen in Sentry logs:
![screen shot 2016-04-11 at 11 01 27 am](https://cloud.githubusercontent.com/assets/133924/14431725/f9c43c30-ffd4-11e5-85c7-94e5addebc22.png)

Sentry on-premise backend version is `8.3.1`.

**Comment by ye** [comment]
My PR #13 might be a potential fix.

**Comment by qrof** [comment]
I confirm it's a fix :)

**Comment by ye** [comment]
Thanks @qrof !

**Comment by creatyvtype** [comment]
Any idea when this fix might be merged in? I keep getting the error as well.
