### ISSUE TITLE
Generated event ids are not random

### ISSUE THREAD

**Issue by defusevenue** [cloudflare/raven-lua#35]
I ran into a weird issue where Raven would generate the same event ids over and over again. It would also generate the same set ids in a specific order.

I resolved it by using replacing the `math.random()` function in `util.generate_event_id()` with `resty.random` from `lua-resty-string` which is bundled into Openresty.

Solution I came up with:
```lua
local resty_random = require 'resty.random'
local str = require 'resty.string'

function _M.generate_event_id()
    return str.to_hex(resty_random.bytes(16))
end
```

Is there an explanation to why this was happening?

**Comment by jdesgats** [comment]
This is because the PRNG needs to be seeded with `math.randomseed`, otherwise you will always use the default seed that produce the same suite of values. This is outside of the scope of this library and should be done globally during initialization.

**Comment by cycomachead** [comment]
It's fine that I need to set it globally, but it would have helped a lot if this need were documented.
