### ISSUE TITLE
Update to Sentry protocol 5

### ISSUE THREAD

**Issue by mattrobenolt** [cloudflare/raven-lua#5]
The highest we have is 6, but it's brand new, so let's start with 5.

I plan on doing this btw.

**Comment by dknecht** [comment]
Thanks Matt.  We aren't currently using this in production because it was buggy.  This is good time for us to get if fixed up and back out there.

**Comment by mattrobenolt** [comment]
Well, let's see what we can do to make it better. :)

**Comment by calio** [comment]
Great! I hope I can do this myself but I'm currently busy with other things. But if you have any suggestions and questions, feel free to ask me.

**Comment by LewisJEllis** [comment]
This can be closed as per #13.
